ushort[] pointer pass test from FNA compatibility
SDL_CalculateGammaRamp and some other functions are
passed a ushort[] array to fill, which currently causes:

Error: Type 'System.UInt16[]' cannot be marshalled